### ISSUE TITLE
User testing 

### ISSUE THREAD

**Issue by renatadev** [fac18/signpost#2]
**User Testing Script:**

We are prototyping an app for the use of people who may be facing homelessness to find services in the Islington area.
Would you be interested in trying it out for 2 minutes and giving us some feedback?
This is the first draft of the prototype so there is a lot more that needs to be changed - please be honest and open about things you think need to be added/altered.
The buttons may not function as they would on a real app but you can find a journey through to see all the pages the app offers.
We will provide some scenarios for you to navigate the prototype.
We are testing the app, not you, so don’t feel embarrassed if you don’t understand something, it’s our fault not yours!

**Initial questions:** 

Do you often use apps?
Do you consider yourself good with technology?
Do you access the internet more often on your phone or on your desktop?

**Scenarios:** 

1. You are a woman with children, but no pets, and would like to see places that provide showers.
1.1. How would you find out more information about the service?
2. You are a man with a pet and you need to find free medical services for your dog. 
3. You work for a charity in Islington which has just started providing popup shower stalls for the homeless which you would like to feature on the map. How would you add this service?
4. You have tried to access the Sanktus free showers and have encountered a problem. How do you report this? 

**After following the scenarios:**

Let the user explore the app and ask what does each page do? Let them find out by themselves.

**Post-testing questions:**

Was there anything that you didn't understand about the website?
Was there anything you thought was unnecessary? 
Was there anything you thought was missing?
Was there anything that you liked in particular?
Did you find all clickable elements obvious enough?
How did you find navigating throughout the website? Was it intuitive or did you need to ask questions?

**Comment by renatajarmova** [comment]
**User Testing Results**
 
**Builder**: (No welcome page in this demo)
The questions page was unclear and unintuitive
The no button should be an X not a minus
Used the map as it should be, selecting the pins for the services
The buttons were straight forward
The edit button was unclear on the services page and that it shouldn’t be the only option on the page -> we should push people towards a particular direction like contacting them 
He thought the “edit” button was to contact them
Suggested including a contacts button

**Bookshop Owner:** 
Suggested an arrow on the map to indicate the service appearing below
On service page, asked if he would be expected to copy the address into a map or would there be a route given
Didn’t like that we were immediately asking for his data instead of helping him
Suggested adding directions to the app through a connection to google maps: can save the location that way too
Sending an article about privacy from New York Times - location data storage
The skip button is not obvious
There could be a scroll button -> arrows encouraging you to scroll down
There should be a different welcome process for organisations who might want to add a service
If reporting a problem, the edit button should be a different icon or there should be more instruction
Should add a report/edit button to first page
SKIP/REPORT/ADD?
The questions page is strange when there is no information given about the app - asking questions about the user before sharing anything
Clean and simple look
Symbols could light up with a colour
Purple comes to mind
Orange or green but pale tones
Suggests that animals should remain an option even for those without pets
Should include links for green spaces/parks/free spaces in london (southbank etc)
Great idea!
Simple and uncluttered - good symbols
 
**The big issue - receptionist?:**
Confused about the areas covered by the app. We had to clarify that it would only be for Islignton 
Found the app very user friendly and not wordy
It wasn’t clear how to go back to the other services
It was not obvious at all how to add a new service
Making an edit/suggestion was more obvious
 
**Police (2) officers:** 
Prioritise the order of the services. First things first :) 
Not easy/clear how to go back once you clicked onto something
Not idea at all that you can add a new service, once given some guidance they found the + button very easily
Suggest to add a charities/streetlink section as homeless like to refer to things/places that they already know about.
Add directions: once clicking into a place it would be nice to be able to find a way to get to the place. Suggested a map called “Garmin Maps” which should be a very easy/simple way to give directions to people.
Suggested to add more color to it without obviously realising that it was only a prototype
Adding a way of finding transport services - to buy oyster cards, etc.
Suggested adding clothes section - said homeless people go through clothes quite fast
 
**Big Issue Vendor 1:**
English level too low to understand what we were trying to do
Very friendly!
Had a brand new smartphone which was very interesting to see.

**Big Issue Vendor 2:**
Aged about 50??
Possibly didn’t 100% understand what we were trying to do, spoke more generally, didn’t actually look at the prototype
Spoke about how being homeless is difficult and services are inadequate
Very mistrustful and negative view of politicians and service providers
Mentioned that Cornwall has no services, Devon is better (insight into how geography affects availability of services)
Only knows about services by word of mouth, no use of tech at all
 
**Big Issue Vendor 3:**
Aged about 60??
Very supportive of the idea, said it was useful
He said he wouldn’t describe himself as tech savvy but could use things
He had a small tablet
He found the interface easy to use
He said finding medical services would be a higher priority for him (had a bypass a year or two ago and has problems with one ear)
Found the app very useful and asked us to develop it more.

**Cafe Woman 1**
Not digitally native - felt v uncomfortable with tech
Liked the icons page - clear and understood how this worked
Map unclear - maybe bouncing pins to encourage engagement or an instruction which says “click on an icon for more information”
Didn’t type in search bar at all 
Turn add button on map into a help button to explain pins/search

**Cafe woman 2** 
Understood intuitively how the app worked
Wanted to know whether she would be able to use it to give help to homeless people
Didn’t type in search bar at all
